# Use lightweight Node.js image
FROM node:20-alpine

# Set working directory inside container
WORKDIR /usr/src/app

# Copy package.json & package-lock.json for caching
COPY package*.json ./

# Skip installing dependencies at build time
# RUN npm install

# Copy all backend files
COPY . .

# Expose backend port
EXPOSE 5000

# Start backend in dev mode with nodemon and install deps at runtime
CMD ["sh", "-c", "npm install && npm run dev"]
