const projectIdeas = [
  {
    id: "1",
    slug: "kenya-social",
    title: "Kenya Social",
    description: "A homegrown social media platform built exclusively for Kenyans to connect, share, and communicate.",
    fullDescription: "Kenya Social is a dedicated social media platform designed specifically for the Kenyan community. It provides a space for Kenyans to connect, share updates, discuss local issues, promote businesses, and celebrate culture without relying on foreign platforms. Features include posts, stories, groups, marketplace, and local news aggregation.",
    problem: "Kenyans are heavily dependent on foreign social media platforms like Facebook, Twitter, and Instagram where content is often irrelevant to local context, data is stored abroad, and there's no sense of community ownership.",
    solution: "A locally-owned platform that understands Kenyan culture, prioritizes local content, keeps data within the country, and fosters genuine community connections.",
    technologies: ["Next.js", "TypeScript", "PostgreSQL", "Prisma", "Redis", "WebSockets", "Tailwind CSS", "NextAuth", "Docker", "AWS"],
    complexity: "advanced",
    status: "planning",
    seekingCollaborators: true,
    estimatedTimeline: "8 months",
    category: "social",
    motivation: "I believe Kenyans deserve a digital space that truly belongs to them, where our stories, conversations, and data remain under our control.",
    features: [
      "User profiles with verification badges",
      "Posts with images, videos, and text",
      "Stories that disappear after 24 hours",
      "Private and public groups",
      "Local marketplace for buying/selling",
      "Events creation and discovery",
      "Local news aggregation",
      "Real-time messaging",
      "Content in English and Swahili",
      "Data centers in Kenya"
    ],
    collaboratorsNeeded: ["Senior React/Next.js developer", "Mobile developer (React Native)", "DevOps engineer", "UI/UX designer", "Community manager"],
    githubUrl: "https://github.com/stephenmuli/kenya-social",
    discussionUrl: "https://github.com/stephenmuli/kenya-social/discussions",
    dockerImages: ["stephenmuli/kenya-social-api:latest", "stephenmuli/kenya-social-web:latest"],
    architecture: "Microservices architecture with separate services for auth, posts, messaging, and marketplace. Redis for real-time features.",
    priority: "high",
    dateAdded: "2024-03-01"
  },
  {
    id: "2",
    slug: "isp-billing-system",
    title: "ISP Billing Engine",
    description: "Comprehensive billing and management system for ISPs with MikroTik and Ruijie integration via custom APIs.",
    fullDescription: "ISP Billing Engine is a powerful solution for Internet Service Providers to manage customers, automate billing, and control network access. It integrates directly with MikroTik RouterOS and Ruijie devices through custom APIs, enabling automatic bandwidth management, quota enforcement, and payment synchronization. Development has started with core billing features.",
    problem: "ISPs in Kenya struggle with manual customer management, billing errors, and complex network device configurations. Existing solutions are either too expensive or don't integrate well with local payment methods.",
    solution: "A cost-effective billing system with deep integration with MikroTik and Ruijie devices, supporting M-Pesa payments and automated provisioning.",
    technologies: ["Python", "FastAPI", "Celery", "Redis", "PostgreSQL", "MikroTik API", "Ruijie API", "React", "Docker", "M-Pesa API"],
    complexity: "advanced",
    status: "started",
    seekingCollaborators: true,
    estimatedTimeline: "6 months remaining",
    category: "isp",
    motivation: "Local ISPs in my area have told me about the challenges of managing customers and devices. An integrated solution would transform their operations.",
    features: [
      "Customer management and CRM",
      "Automated billing and invoicing",
      "M-Pesa payment integration",
      "Bandwidth management via MikroTik API",
      "Ruijie device integration",
      "Quota management and enforcement",
      "Network usage monitoring",
      "Automated account suspension/reconnection",
      "Customer portal for self-service",
      "Detailed analytics and reports"
    ],
    collaboratorsNeeded: ["Python backend developer", "Network engineer with MikroTik experience", "Frontend developer", "DevOps engineer"],
    githubUrl: "https://github.com/stephenmuli/isp-billing",
    discussionUrl: "https://github.com/stephenmuli/isp-billing/discussions",
    dockerImages: ["stephenmuli/isp-api:latest", "stephenmuli/isp-worker:latest", "stephenmuli/isp-web:latest"],
    architecture: "Event-driven architecture with Celery workers. Separate containers for API, workers, and web interface. MikroTik API integration layer completed.",
    priority: "high",
    dateAdded: "2024-02-20"
  },
  {
    id: "3",
    slug: "smart-scheduler",
    title: "Smart Meeting Scheduler",
    description: "Intelligent scheduling system for booking meetings, managing availability, and optimizing time slots across teams.",
    fullDescription: "Smart Scheduler is an AI-powered meeting coordination tool that eliminates the back-and-forth of finding meeting times. It integrates with Google Calendar, Outlook, and other calendar services to find optimal meeting times, send invitations, and manage room bookings. The core scheduling engine is complete with just final UI polish and testing remaining.",
    problem: "Professionals waste hours coordinating meeting times across different time zones and calendars. The email ping-pong for scheduling is inefficient and frustrating.",
    solution: "An intelligent scheduler that automatically finds optimal meeting times based on participants' availability, preferences, and meeting requirements.",
    technologies: ["Next.js", "TypeScript", "Node.js", "PostgreSQL", "Redis", "Google Calendar API", "Microsoft Graph API", "WebSockets", "Docker"],
    complexity: "intermediate",
    status: "almost-complete",
    seekingCollaborators: false,
    estimatedTimeline: "2 weeks remaining",
    category: "scheduling",
    motivation: "As a freelancer, I waste at least 2 hours every week just scheduling meetings. This tool would give that time back.",
    features: [
      "Multi-calendar integration (Google, Outlook, Apple)",
      "Intelligent time slot suggestions",
      "Meeting poll creation",
      "Room/resource booking",
      "Time zone intelligence",
      "Recurring meeting optimization",
      "Conflict resolution",
      "Calendar analytics",
      "Meeting reminders",
      "API for third-party integration"
    ],
    collaboratorsNeeded: [],
    githubUrl: "https://github.com/stephenmuli/smart-scheduler",
    discussionUrl: "https://github.com/stephenmuli/smart-scheduler/discussions",
    dockerImages: ["stephenmuli/scheduler-api:latest", "stephenmuli/scheduler-web:latest"],
    architecture: "Microservices with Redis for session management and job queues. Core scheduling algorithm completed.",
    priority: "medium",
    dateAdded: "2024-02-25"
  },
  {
    id: "4",
    slug: "efootball-kenya",
    title: "eFootball Kenya Arena",
    description: "A platform for Konami eFootball gamers to buy/sell accounts, form teams, organize tournaments, and connect with other players.",
    fullDescription: "eFootball Kenya Arena is the ultimate hub for Kenyan eFootball gamers. It provides a marketplace for buying and selling Konami accounts, team formation tools, tournament organization, player matching, and community features. Whether you're a casual player or aspiring pro, this platform connects you with the growing eFootball community in Kenya.",
    problem: "Kenyan eFootball gamers are scattered across different platforms with no central place to find teammates, buy/sell accounts, or participate in local tournaments. Existing international platforms don't cater to the local scene.",
    solution: "A dedicated platform that brings the Kenyan eFootball community together, facilitating account trading, team formation, and competitive play.",
    technologies: ["Next.js", "TypeScript", "Node.js", "PostgreSQL", "Prisma", "WebSockets", "Redis", "Tailwind CSS", "Docker"],
    complexity: "intermediate",
    status: "seeking-collaborators",
    seekingCollaborators: true,
    estimatedTimeline: "4 months",
    category: "gaming",
    motivation: "As an eFootball enthusiast myself, I've seen the struggle Kenyan players face trying to connect and compete. This platform will build our local esports scene.",
    features: [
      "Account marketplace with verification",
      "Secure escrow system for transactions",
      "Team formation and management",
      "Tournament creation and brackets",
      "Player rankings and stats",
      "Match scheduling",
      "Gamer profiles with achievements",
      "Discord integration",
      "Live match streaming links",
      "Community forums"
    ],
    collaboratorsNeeded: ["Full-stack developer", "UI/UX designer with gaming aesthetic", "Community manager with esports experience", "Blockchain developer for escrow (optional)"],
    githubUrl: "https://github.com/stephenmuli/efootball-kenya",
    discussionUrl: "https://github.com/stephenmuli/efootball-kenya/discussions",
    dockerImages: ["stephenmuli/efootball-api:latest", "stephenmuli/efootball-web:latest"],
    architecture: "Real-time features using WebSockets. Redis for caching player data and matchmaking queues.",
    priority: "high",
    dateAdded: "2024-03-05"
  },
  {
    id: "5",
    slug: "attendance-tracker",
    title: "GPS Attendance Tracker",
    description: "GPS-based attendance tracking system for universities and businesses that verifies physical presence at location.",
    fullDescription: "A revolutionary attendance system that uses GPS technology to verify that individuals are physically present at a specific location before marking attendance. Perfect for universities wanting to ensure students are actually in class, or businesses with field employees who need to verify site visits. I'm building this solo with plans to expand.",
    problem: "Traditional attendance systems can be easily faked - students mark friends present, employees claim to be at sites they never visited, and remote work verification is challenging.",
    solution: "A GPS-verified attendance system that requires physical presence at designated locations, with time windows and geofencing to prevent fraud.",
    technologies: ["React Native", "Node.js", "PostgreSQL", "Redis", "Google Maps API", "WebSockets", "Docker", "TypeScript"],
    complexity: "intermediate",
    status: "planning",
    seekingCollaborators: false,
    estimatedTimeline: "3 months",
    category: "mobile",
    motivation: "I want to solve the real problem of attendance fraud that affects universities and businesses. This system will bring accountability.",
    features: [
      "GPS location verification",
      "Geofencing for specific locations",
      "Time-based attendance windows",
      "QR code backup system",
      "Real-time attendance dashboard",
      "Report generation",
      "Leave and exception management",
      "Push notifications",
      "Offline mode with sync",
      "Multi-organization support"
    ],
    collaboratorsNeeded: [],
    githubUrl: "https://github.com/stephenmuli/attendance-tracker",
    discussionUrl: "https://github.com/stephenmuli/attendance-tracker/discussions",
    dockerImages: ["stephenmuli/attendance-api:latest"],
    architecture: "Mobile-first approach with React Native. Location data encrypted and verified server-side.",
    priority: "medium",
    dateAdded: "2024-03-08"
  },
  {
    id: "6",
    slug: "chama-management-system",
    title: "Chama Manager Pro",
    description: "A comprehensive management system for investment groups (Chamas), merry-go-rounds, and fundraising circles.",
    fullDescription: "Chama Manager Pro is a complete financial management solution for investment groups in Kenya. It handles member contributions, loan management, fine tracking, dividend calculations, and generates financial reports. The system includes a mobile app for members to track their savings, request loans, and vote on group decisions.",
    problem: "Most Chamas (investment groups) in Kenya still use manual record-keeping or spreadsheets, leading to errors, disputes, and lack of transparency in financial management.",
    solution: "A digital platform that automates Chama operations, provides real-time financial visibility, and ensures transparent record-keeping for all members.",
    technologies: ["Next.js", "TypeScript", "PostgreSQL", "Prisma", "Tailwind CSS", "NextAuth", "React Native", "WebSockets", "Redis"],
    complexity: "advanced",
    status: "planning",
    seekingCollaborators: true,
    estimatedTimeline: "6 months",
    category: "fintech",
    motivation: "My mother's Chama has had disputes over missing records. A proper system would prevent this and help groups grow their investments confidently.",
    features: [
      "Member management and profiles",
      "Contribution tracking with reminders",
      "Loan application and approval workflow",
      "Fine management for late payments",
      "Dividend calculations and distribution",
      "Meeting minutes and voting system",
      "Financial reports and analytics",
      "Mobile app for members",
      "SMS notifications",
      "Audit trail for all transactions"
    ],
    collaboratorsNeeded: ["Mobile developer (React Native)", "Backend developer (Node.js/PostgreSQL)", "UI/UX designer", "Financial advisor for compliance"],
    githubUrl: "https://github.com/stephenmuli/chama-manager",
    discussionUrl: "https://github.com/stephenmuli/chama-manager/discussions",
    dockerImages: ["stephenmuli/chama-api:latest", "stephenmuli/chama-web:latest"],
    architecture: "Microservices with Docker containers. API Gateway pattern with Redis caching.",
    priority: "high",
    dateAdded: "2024-02-15"
  }
];

module.exports = projectIdeas;
